// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getEventsApiVehiclesEventsGet, getFinancialStatsApiSimulationFinancialStatsGet, getLocationsApiSimulationLocationsGet, getPositionsApiTrackingPositionsGet, getQuickStatsApiVehiclesQuickStatsGet, getSimulationTimeApiSimulationTimeGet, getVehicleCountApiVehiclesCountGet, getVehiclePositionsApiSimulationVehiclesPositionsGet, type Options, recalculateTruckApiTrackingRecalculatePost, updateSpeedApiTrackingSpeedPost } from '../sdk.gen';
import type { GetEventsApiVehiclesEventsGetData, GetFinancialStatsApiSimulationFinancialStatsGetData, GetLocationsApiSimulationLocationsGetData, GetPositionsApiTrackingPositionsGetData, GetQuickStatsApiVehiclesQuickStatsGetData, GetSimulationTimeApiSimulationTimeGetData, GetVehicleCountApiVehiclesCountGetData, GetVehiclePositionsApiSimulationVehiclesPositionsGetData, RecalculateTruckApiTrackingRecalculatePostData, RecalculateTruckApiTrackingRecalculatePostError, UpdateSpeedApiTrackingSpeedPostData, UpdateSpeedApiTrackingSpeedPostError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getVehicleCountApiVehiclesCountGetQueryKey = (options?: Options<GetVehicleCountApiVehiclesCountGetData>) => createQueryKey('getVehicleCountApiVehiclesCountGet', options);

/**
 * Get Vehicle Count
 *
 * Get total count of vehicles
 */
export const getVehicleCountApiVehiclesCountGetOptions = (options?: Options<GetVehicleCountApiVehiclesCountGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVehicleCountApiVehiclesCountGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getVehicleCountApiVehiclesCountGetQueryKey(options)
    });
};

export const getQuickStatsApiVehiclesQuickStatsGetQueryKey = (options?: Options<GetQuickStatsApiVehiclesQuickStatsGetData>) => createQueryKey('getQuickStatsApiVehiclesQuickStatsGet', options);

/**
 * Get Quick Stats
 *
 * Get quick statistics for dashboard
 */
export const getQuickStatsApiVehiclesQuickStatsGetOptions = (options?: Options<GetQuickStatsApiVehiclesQuickStatsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getQuickStatsApiVehiclesQuickStatsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getQuickStatsApiVehiclesQuickStatsGetQueryKey(options)
    });
};

export const getEventsApiVehiclesEventsGetQueryKey = (options?: Options<GetEventsApiVehiclesEventsGetData>) => createQueryKey('getEventsApiVehiclesEventsGet', options);

/**
 * Get Events
 *
 * Get recent events/logs
 */
export const getEventsApiVehiclesEventsGetOptions = (options?: Options<GetEventsApiVehiclesEventsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getEventsApiVehiclesEventsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getEventsApiVehiclesEventsGetQueryKey(options)
    });
};

export const getVehiclePositionsApiSimulationVehiclesPositionsGetQueryKey = (options?: Options<GetVehiclePositionsApiSimulationVehiclesPositionsGetData>) => createQueryKey('getVehiclePositionsApiSimulationVehiclesPositionsGet', options);

/**
 * Get Vehicle Positions
 *
 * Get all vehicles with randomly assigned positions from the locations database.
 * Each call randomly assigns vehicles to locations to simulate movement.
 */
export const getVehiclePositionsApiSimulationVehiclesPositionsGetOptions = (options?: Options<GetVehiclePositionsApiSimulationVehiclesPositionsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getVehiclePositionsApiSimulationVehiclesPositionsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getVehiclePositionsApiSimulationVehiclesPositionsGetQueryKey(options)
    });
};

export const getLocationsApiSimulationLocationsGetQueryKey = (options?: Options<GetLocationsApiSimulationLocationsGetData>) => createQueryKey('getLocationsApiSimulationLocationsGet', options);

/**
 * Get Locations
 */
export const getLocationsApiSimulationLocationsGetOptions = (options?: Options<GetLocationsApiSimulationLocationsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getLocationsApiSimulationLocationsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getLocationsApiSimulationLocationsGetQueryKey(options)
    });
};

export const getFinancialStatsApiSimulationFinancialStatsGetQueryKey = (options?: Options<GetFinancialStatsApiSimulationFinancialStatsGetData>) => createQueryKey('getFinancialStatsApiSimulationFinancialStatsGet', options);

/**
 * Get Financial Stats
 *
 * Get financial statistics from the simulation results
 */
export const getFinancialStatsApiSimulationFinancialStatsGetOptions = (options?: Options<GetFinancialStatsApiSimulationFinancialStatsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getFinancialStatsApiSimulationFinancialStatsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getFinancialStatsApiSimulationFinancialStatsGetQueryKey(options)
    });
};

export const getSimulationTimeApiSimulationTimeGetQueryKey = (options?: Options<GetSimulationTimeApiSimulationTimeGetData>) => createQueryKey('getSimulationTimeApiSimulationTimeGet', options);

/**
 * Get Simulation Time
 *
 * Get current simulation time and status from the coordinator
 */
export const getSimulationTimeApiSimulationTimeGetOptions = (options?: Options<GetSimulationTimeApiSimulationTimeGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSimulationTimeApiSimulationTimeGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSimulationTimeApiSimulationTimeGetQueryKey(options)
    });
};

export const getPositionsApiTrackingPositionsGetQueryKey = (options?: Options<GetPositionsApiTrackingPositionsGetData>) => createQueryKey('getPositionsApiTrackingPositionsGet', options);

/**
 * Get Positions
 */
export const getPositionsApiTrackingPositionsGetOptions = (options?: Options<GetPositionsApiTrackingPositionsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getPositionsApiTrackingPositionsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getPositionsApiTrackingPositionsGetQueryKey(options)
    });
};

/**
 * Update Speed
 */
export const updateSpeedApiTrackingSpeedPostMutation = (options?: Partial<Options<UpdateSpeedApiTrackingSpeedPostData>>): UseMutationOptions<unknown, UpdateSpeedApiTrackingSpeedPostError, Options<UpdateSpeedApiTrackingSpeedPostData>> => {
    const mutationOptions: UseMutationOptions<unknown, UpdateSpeedApiTrackingSpeedPostError, Options<UpdateSpeedApiTrackingSpeedPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateSpeedApiTrackingSpeedPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Recalculate Truck
 */
export const recalculateTruckApiTrackingRecalculatePostMutation = (options?: Partial<Options<RecalculateTruckApiTrackingRecalculatePostData>>): UseMutationOptions<unknown, RecalculateTruckApiTrackingRecalculatePostError, Options<RecalculateTruckApiTrackingRecalculatePostData>> => {
    const mutationOptions: UseMutationOptions<unknown, RecalculateTruckApiTrackingRecalculatePostError, Options<RecalculateTruckApiTrackingRecalculatePostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recalculateTruckApiTrackingRecalculatePost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
