// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetEventsApiVehiclesEventsGetData, GetEventsApiVehiclesEventsGetErrors, GetEventsApiVehiclesEventsGetResponses, GetFinancialStatsApiSimulationFinancialStatsGetData, GetFinancialStatsApiSimulationFinancialStatsGetResponses, GetLocationsApiSimulationLocationsGetData, GetLocationsApiSimulationLocationsGetResponses, GetPositionsApiTrackingPositionsGetData, GetPositionsApiTrackingPositionsGetResponses, GetQuickStatsApiVehiclesQuickStatsGetData, GetQuickStatsApiVehiclesQuickStatsGetResponses, GetSimulationTimeApiSimulationTimeGetData, GetSimulationTimeApiSimulationTimeGetResponses, GetVehicleCountApiVehiclesCountGetData, GetVehicleCountApiVehiclesCountGetResponses, GetVehiclePositionsApiSimulationVehiclesPositionsGetData, GetVehiclePositionsApiSimulationVehiclesPositionsGetResponses, RecalculateTruckApiTrackingRecalculatePostData, RecalculateTruckApiTrackingRecalculatePostErrors, RecalculateTruckApiTrackingRecalculatePostResponses, UpdateSpeedApiTrackingSpeedPostData, UpdateSpeedApiTrackingSpeedPostErrors, UpdateSpeedApiTrackingSpeedPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Vehicle Count
 *
 * Get total count of vehicles
 */
export const getVehicleCountApiVehiclesCountGet = <ThrowOnError extends boolean = false>(options?: Options<GetVehicleCountApiVehiclesCountGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetVehicleCountApiVehiclesCountGetResponses, unknown, ThrowOnError>({
        url: '/api/vehicles/count',
        ...options
    });
};

/**
 * Get Quick Stats
 *
 * Get quick statistics for dashboard
 */
export const getQuickStatsApiVehiclesQuickStatsGet = <ThrowOnError extends boolean = false>(options?: Options<GetQuickStatsApiVehiclesQuickStatsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetQuickStatsApiVehiclesQuickStatsGetResponses, unknown, ThrowOnError>({
        url: '/api/vehicles/quick-stats',
        ...options
    });
};

/**
 * Get Events
 *
 * Get recent events/logs
 */
export const getEventsApiVehiclesEventsGet = <ThrowOnError extends boolean = false>(options?: Options<GetEventsApiVehiclesEventsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetEventsApiVehiclesEventsGetResponses, GetEventsApiVehiclesEventsGetErrors, ThrowOnError>({
        url: '/api/vehicles/events',
        ...options
    });
};

/**
 * Get Vehicle Positions
 *
 * Get all vehicles with randomly assigned positions from the locations database.
 * Each call randomly assigns vehicles to locations to simulate movement.
 */
export const getVehiclePositionsApiSimulationVehiclesPositionsGet = <ThrowOnError extends boolean = false>(options?: Options<GetVehiclePositionsApiSimulationVehiclesPositionsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetVehiclePositionsApiSimulationVehiclesPositionsGetResponses, unknown, ThrowOnError>({
        url: '/api/simulation/vehicles/positions',
        ...options
    });
};

/**
 * Get Locations
 */
export const getLocationsApiSimulationLocationsGet = <ThrowOnError extends boolean = false>(options?: Options<GetLocationsApiSimulationLocationsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetLocationsApiSimulationLocationsGetResponses, unknown, ThrowOnError>({
        url: '/api/simulation/locations',
        ...options
    });
};

/**
 * Get Financial Stats
 *
 * Get financial statistics from the simulation results
 */
export const getFinancialStatsApiSimulationFinancialStatsGet = <ThrowOnError extends boolean = false>(options?: Options<GetFinancialStatsApiSimulationFinancialStatsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetFinancialStatsApiSimulationFinancialStatsGetResponses, unknown, ThrowOnError>({
        url: '/api/simulation/financial-stats',
        ...options
    });
};

/**
 * Get Simulation Time
 *
 * Get current simulation time and status from the coordinator
 */
export const getSimulationTimeApiSimulationTimeGet = <ThrowOnError extends boolean = false>(options?: Options<GetSimulationTimeApiSimulationTimeGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSimulationTimeApiSimulationTimeGetResponses, unknown, ThrowOnError>({
        url: '/api/simulation/time',
        ...options
    });
};

/**
 * Get Positions
 */
export const getPositionsApiTrackingPositionsGet = <ThrowOnError extends boolean = false>(options?: Options<GetPositionsApiTrackingPositionsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetPositionsApiTrackingPositionsGetResponses, unknown, ThrowOnError>({
        url: '/api/tracking/positions',
        ...options
    });
};

/**
 * Update Speed
 */
export const updateSpeedApiTrackingSpeedPost = <ThrowOnError extends boolean = false>(options: Options<UpdateSpeedApiTrackingSpeedPostData, ThrowOnError>) => {
    return (options.client ?? client).post<UpdateSpeedApiTrackingSpeedPostResponses, UpdateSpeedApiTrackingSpeedPostErrors, ThrowOnError>({
        url: '/api/tracking/speed',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Recalculate Truck
 */
export const recalculateTruckApiTrackingRecalculatePost = <ThrowOnError extends boolean = false>(options: Options<RecalculateTruckApiTrackingRecalculatePostData, ThrowOnError>) => {
    return (options.client ?? client).post<RecalculateTruckApiTrackingRecalculatePostResponses, RecalculateTruckApiTrackingRecalculatePostErrors, ThrowOnError>({
        url: '/api/tracking/recalculate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
