// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * EventLogEntry
 */
export type EventLogEntry = {
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Type
     */
    type: string;
    /**
     * Message
     */
    message: string;
    /**
     * Vehicle Id
     */
    vehicle_id: number | null;
    /**
     * Registration Number
     */
    registration_number: string | null;
    /**
     * Severity
     */
    severity: string;
};

/**
 * EventLogResponse
 */
export type EventLogResponse = {
    /**
     * Events
     */
    events: Array<EventLogEntry>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * FinancialStatsResponse
 */
export type FinancialStatsResponse = {
    /**
     * Relocation Cost Pln
     */
    relocation_cost_pln: number;
    /**
     * Service Cost Pln
     */
    service_cost_pln: number;
    /**
     * Penalty Cost Pln
     */
    penalty_cost_pln: number;
    /**
     * Total Cost Pln
     */
    total_cost_pln: number;
    /**
     * Routes Assigned
     */
    routes_assigned: number;
    /**
     * Vehicles Used
     */
    vehicles_used: number;
    /**
     * Total Services
     */
    total_services: number;
    /**
     * Total Distance Km
     */
    total_distance_km: number;
    /**
     * Data Available
     */
    data_available: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LocationData
 */
export type LocationData = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Lat
     */
    lat: number;
    /**
     * Long
     */
    long: number;
    /**
     * Is Hub
     */
    is_hub: boolean;
};

/**
 * LocationsResponse
 */
export type LocationsResponse = {
    /**
     * Locations
     */
    locations: Array<LocationData>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * QuickStatsResponse
 */
export type QuickStatsResponse = {
    /**
     * Top 3 Lease Ending
     */
    top_3_lease_ending: Array<VehicleLeaseInfo>;
    /**
     * Top 3 Service Needed
     */
    top_3_service_needed: Array<VehicleServiceInfo>;
    /**
     * Vehicles Over Limit
     */
    vehicles_over_limit: number;
    /**
     * Total Services Needed
     */
    total_services_needed: number;
    /**
     * Average Odometer
     */
    average_odometer: number;
    /**
     * Total Km Driven
     */
    total_km_driven: number;
    /**
     * Vehicles Needing Replacement
     */
    vehicles_needing_replacement: number;
    /**
     * Average Days To Lease End
     */
    average_days_to_lease_end: number;
};

/**
 * RecalculateRequest
 */
export type RecalculateRequest = {
    /**
     * Truck Id
     */
    truck_id: number;
};

/**
 * SimulationTimeResponse
 */
export type SimulationTimeResponse = {
    /**
     * Current Time
     */
    current_time: string;
    /**
     * Simulation Start
     */
    simulation_start: string;
    /**
     * Simulation Speed
     */
    simulation_speed: number;
    /**
     * Is Running
     */
    is_running: boolean;
    /**
     * Elapsed Days
     */
    elapsed_days: number;
};

/**
 * SpeedUpdate
 */
export type SpeedUpdate = {
    /**
     * Speed Multiplier
     */
    speed_multiplier: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VehicleCountResponse
 */
export type VehicleCountResponse = {
    /**
     * Count
     */
    count: number;
};

/**
 * VehicleLeaseInfo
 */
export type VehicleLeaseInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Registration Number
     */
    registration_number: string;
    /**
     * Brand
     */
    brand: string;
    /**
     * Leasing End Date
     */
    leasing_end_date: string;
    /**
     * Days Remaining
     */
    days_remaining: number;
};

/**
 * VehiclePosition
 */
export type VehiclePosition = {
    /**
     * Id
     */
    id: number;
    /**
     * Registration Number
     */
    registration_number: string;
    /**
     * Brand
     */
    brand: string;
    /**
     * Latitude
     */
    latitude: number;
    /**
     * Longitude
     */
    longitude: number;
    /**
     * Location Name
     */
    location_name: string;
    /**
     * Current Odometer Km
     */
    current_odometer_km: number;
    /**
     * Service Interval Km
     */
    service_interval_km: number;
};

/**
 * VehiclePositionsResponse
 */
export type VehiclePositionsResponse = {
    /**
     * Vehicles
     */
    vehicles: Array<VehiclePosition>;
    /**
     * Total Count
     */
    total_count: number;
};

/**
 * VehicleServiceInfo
 */
export type VehicleServiceInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Registration Number
     */
    registration_number: string;
    /**
     * Brand
     */
    brand: string;
    /**
     * Current Odometer Km
     */
    current_odometer_km: number;
    /**
     * Service Interval Km
     */
    service_interval_km: number;
    /**
     * Km Until Service
     */
    km_until_service: number;
};

export type GetVehicleCountApiVehiclesCountGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vehicles/count';
};

export type GetVehicleCountApiVehiclesCountGetResponses = {
    /**
     * Successful Response
     */
    200: VehicleCountResponse;
};

export type GetVehicleCountApiVehiclesCountGetResponse = GetVehicleCountApiVehiclesCountGetResponses[keyof GetVehicleCountApiVehiclesCountGetResponses];

export type GetQuickStatsApiVehiclesQuickStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/vehicles/quick-stats';
};

export type GetQuickStatsApiVehiclesQuickStatsGetResponses = {
    /**
     * Successful Response
     */
    200: QuickStatsResponse;
};

export type GetQuickStatsApiVehiclesQuickStatsGetResponse = GetQuickStatsApiVehiclesQuickStatsGetResponses[keyof GetQuickStatsApiVehiclesQuickStatsGetResponses];

export type GetEventsApiVehiclesEventsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Severity
         */
        severity?: string | null;
    };
    url: '/api/vehicles/events';
};

export type GetEventsApiVehiclesEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEventsApiVehiclesEventsGetError = GetEventsApiVehiclesEventsGetErrors[keyof GetEventsApiVehiclesEventsGetErrors];

export type GetEventsApiVehiclesEventsGetResponses = {
    /**
     * Successful Response
     */
    200: EventLogResponse;
};

export type GetEventsApiVehiclesEventsGetResponse = GetEventsApiVehiclesEventsGetResponses[keyof GetEventsApiVehiclesEventsGetResponses];

export type GetVehiclePositionsApiSimulationVehiclesPositionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/simulation/vehicles/positions';
};

export type GetVehiclePositionsApiSimulationVehiclesPositionsGetResponses = {
    /**
     * Successful Response
     */
    200: VehiclePositionsResponse;
};

export type GetVehiclePositionsApiSimulationVehiclesPositionsGetResponse = GetVehiclePositionsApiSimulationVehiclesPositionsGetResponses[keyof GetVehiclePositionsApiSimulationVehiclesPositionsGetResponses];

export type GetLocationsApiSimulationLocationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/simulation/locations';
};

export type GetLocationsApiSimulationLocationsGetResponses = {
    /**
     * Successful Response
     */
    200: LocationsResponse;
};

export type GetLocationsApiSimulationLocationsGetResponse = GetLocationsApiSimulationLocationsGetResponses[keyof GetLocationsApiSimulationLocationsGetResponses];

export type GetFinancialStatsApiSimulationFinancialStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/simulation/financial-stats';
};

export type GetFinancialStatsApiSimulationFinancialStatsGetResponses = {
    /**
     * Successful Response
     */
    200: FinancialStatsResponse;
};

export type GetFinancialStatsApiSimulationFinancialStatsGetResponse = GetFinancialStatsApiSimulationFinancialStatsGetResponses[keyof GetFinancialStatsApiSimulationFinancialStatsGetResponses];

export type GetSimulationTimeApiSimulationTimeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/simulation/time';
};

export type GetSimulationTimeApiSimulationTimeGetResponses = {
    /**
     * Successful Response
     */
    200: SimulationTimeResponse;
};

export type GetSimulationTimeApiSimulationTimeGetResponse = GetSimulationTimeApiSimulationTimeGetResponses[keyof GetSimulationTimeApiSimulationTimeGetResponses];

export type GetPositionsApiTrackingPositionsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/tracking/positions';
};

export type GetPositionsApiTrackingPositionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateSpeedApiTrackingSpeedPostData = {
    body: SpeedUpdate;
    path?: never;
    query?: never;
    url: '/api/tracking/speed';
};

export type UpdateSpeedApiTrackingSpeedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSpeedApiTrackingSpeedPostError = UpdateSpeedApiTrackingSpeedPostErrors[keyof UpdateSpeedApiTrackingSpeedPostErrors];

export type UpdateSpeedApiTrackingSpeedPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RecalculateTruckApiTrackingRecalculatePostData = {
    body: RecalculateRequest;
    path?: never;
    query?: never;
    url: '/api/tracking/recalculate';
};

export type RecalculateTruckApiTrackingRecalculatePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecalculateTruckApiTrackingRecalculatePostError = RecalculateTruckApiTrackingRecalculatePostErrors[keyof RecalculateTruckApiTrackingRecalculatePostErrors];

export type RecalculateTruckApiTrackingRecalculatePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
